### ISSUE TITLE
libpython3 error on linux

### ISSUE THREAD

**Issue by Barleduq** [AcidWeb/CurseBreaker#346]
This is what I got when I launched CurseBreaker today, after a full restart of my machine.  Cut and pasted from my terminal window.  As far as I am aware, I am up to date on all updates that Ubuntu Software Updater pokes me about, including one that showed up on restart that completed before I even pulled up the terminal window to launch CurseBreaker from.  

───────────────────────────── CurseBreaker v4.2.1 ──────────────────────────────

Updating CurseBreaker...
Update complete! The application will be restarted now.

Changelog:
* Implemented Wrath of the Lich King Classic support

Press any key to continue . . .
[5134] Error loading Python lib '/tmp/_MEImU0Djr/libpython3.10.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEImU0Djr/libpython3.10.so.1.0)

**Comment by AcidWeb** [comment]
Which version of Ubuntu are you using?

**Comment by AcidWeb** [comment]
It looks like ubuntu 20.04+ is supported.

**Comment by AcidWeb** [comment]
Github will remove soon older Actions runners. So build was switched to newer OS versions. Due to nature of PyInstaller that breaks compatibility with older glibc version.

It looks like that starting from v4.3.0 only Ubuntu 20.04+, Debian 11+ and macOS 11+ is supported. And I can't really do anything about it.

If you need to run it on something older I can only suggest to run it from source or build binaries yourself.
