### ISSUE TITLE
Github support

### ISSUE THREAD

**Issue by Obscurax** [AcidWeb/CurseBreaker#41]
Hi, there are some addons out there that are only released on Github. Is it possible to support Github as an addon source aswell?

Love the app, thanks.

**Comment by AcidWeb** [comment]
Duplicate #13

**Comment by torkus** [comment]
@AcidWeb 's comments in that duplicate ticket are spot on - it *is* a QA nightmare.

That said, there are [other addon managers](https://ogri-la.github.io/wow-addon-managers/?preset/name=unfiltered&field/feature-curseforge=&field/maintained=yes&field/windows=&field/eula=&field/feature-tukui=&field/ads=&field/source-available=&field/feature-wowinterface=&field/ui=&field/language=&field/feature-vcs-addons=yes&field/retail=&field/linux=&field/feature-wowace=&field/f-oss=&field/classic=&field/mac=&field/feature-catalog-search=) for WoW that have this feature.

I added support to my own manager for Github hosted addons that fit a very specific set of requirements and that was *a lot* of work, just because of how varied and non-standard the content is on Github. Gitlab (the service) is different again and Gitlab (self hosted) is different yet again!

**Comment by AcidWeb** [comment]
Additionally I don't really see the use case.
If you made addon you need to upload it to WoWI or CF. Or most of generic users will not use it. 
If you are poweruser that need to pull multiple GIT repositories there are better ways to maintain it than this application.

@Obscurax 
https://www.curseforge.com/wow/addons/gearmenu
https://www.curseforge.com/wow/addons/ringmenu
What is wrong with these released?

**Comment by Obscurax** [comment]
Fair enough, I've been using those addons before they got added to CF. Thanks for making me aware they are now available on CF! Also, I did search for this issue before making a new one, I must have overlooked it. Sorry about that.
